
name: Publish GITHUB Packages

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      revision:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Publish Version'
        # Default value if no value is explicitly provided
        default: '1.0-SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Publish package
      run:
        mvn --batch-mode deploy -Drevision=${{github.event.inputs.revision}}
      env:
        GITHUB_TOKEN: ${{ secrets.workflows_token }}
